# Generated by Django 5.1.1 on 2024-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='variant_value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
