# Generated by Django 5.1.1 on 2024-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0005_alter_product_variant_variant_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variants',
            field=models.ManyToManyField(null=True, to='product.product_variant'),
        ),
    ]
